### ISSUE TITLE
Can not start the app

### ISSUE THREAD

**Issue by nejdetckenobi** [cerebroapp/cerebro#353]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 18 - 64 bit
- **Cerebro.app version**: 0.3
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue

I can't launch the application. Yesterday, it was fine. It just slowed down a bit but it's a known issue I think.
I removed it and reinstalled from deb. It still gives the same error.

```
~ ❯ cerebro 
/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:0



Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/opt/Cerebro/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)
```

**Comment by KELiON** [comment]
@nejdetckenobi interesting, there is no code `../dialog` code in application. Can you try to install it from AppImage? Or install previous version?

**Comment by nejdetckenobi** [comment]
I installed 0.2.7 before which gives me the same error. It was AppImage.
When I encountered this error, I removed the AppImage (I simply deleted it) then installed a later version from deb.

Can I do anything to get you enough information to fix this issue? It could be an electron issue I think.

**Comment by nejdetckenobi** [comment]
Ok I can reproduce problem. Normally, when I login, cerebro starts.
I tapped the shortcut several times. Dialog did not showed up but when I check htop, I saw cerebro is running. So, when I try to launch more than one times, this error occurs. 
It masks the actual problem. I don't know why sometimes an error occurs at start. But I tested and got this error when I try to launch more than one.

**Comment by brpaz** [comment]
Hello. I got the same problem when I set Cerebro to autostart on boot. It gives that error and fail to start. If I start it manually from applications menu it works fine.

**Comment by raphaklaus** [comment]
I'm also getting this issue. Ubuntu 17.10

**Comment by nejdetckenobi** [comment]
@raphaklaus @brpaz , seems like @KELiON goes for a vacation somehow. Please use `killall` to kill every single `cerebro` instance and then try to launch again. It won't crash, even if it crashes, it won't be the same error I think.

**Comment by The-Log** [comment]
Same issue. Doesn't run on Ubuntu 17.10.

**Comment by wellcp** [comment]
Problem solved guys.

Take a look at: https://github.com/KELiON/cerebro/issues/354

**Comment by nejdetckenobi** [comment]
@wellcp That's not the issue. It is different.

**Comment by robsaunders** [comment]
This error still occurs two years later...

**Comment by kaungmyatlwin** [comment]
Any update on this issue? I'm having this problem as well.

**Comment by raphaklaus** [comment]
To be honest, I don't use it anymore. Change to Ulauncher. Must admit that I am pretty happy with it.

**Comment by dangerousdino** [comment]
First Install JAVA as per the guide in graylog
    Set SELINUX to permissive to prevent it messing things
    [root@machinename ~]# setenforce permissive
    change to root directory
    [root@machinenamet ~]#cd /root
    Download the rpm
    wget https://github.com/lmenezes/cerebro/releases/download/v0.8.5/cerebro-0.8.5-1.noarch.rpm
    in the same directory run the install
    [root@machinenamet ~]# yum localinstall cerebro-0.8.5-1.noarch.rpm
    allow the program through firewall
    [root@machinenamet ~]# firewall-cmd --zone=public --add-port=9200/tcp --permanent

Notes:
Current issue if it fails to start run this
[root@machinenamet ~]# chown -R cerebro:cerebro /usr/share/cerebro
to enable and start
[root@machinenamet ~]# systemctl enable cerebro
[root@machinenamet ~]# systemctl start cerebro

**Comment by piavgh** [comment]
> To be honest, I don't use it anymore. Change to Ulauncher. Must admit that I am pretty happy with it.

Thank you. Ulauncher is great

**Comment by oguhpereira** [comment]
@nejdetckenobi still having this problem? i wish i could help

**Comment by nejdetckenobi** [comment]
I switched my launcher to alfred. But you can see that people are still having this issue. You can help them

**Comment by oguhpereira** [comment]
@nejdetckenobi yes, thanks

**Comment by carrotfarmer** [comment]
Same issue on Arch :(
