### ISSUE TITLE
Can't start development build: Cannot find module '../tray'

### ISSUE THREAD

**Issue by StefanPahlplatz** [cerebroapp/cerebro#449]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.10
- **Cerebro.app version**: Master branch on 17 feb 2018
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue

After following the steps described in the README, I get the following error in a popup when trying to run ```yarn run dev```.
```
Uncaught Exception:
Error: Cannot find module '../tray'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/stefan/Documents/projects/cerebro/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as Tray] (/home/stefan/Documents/projects/cerebro/node_modules/electron/dist/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at AppTray.show (/home/stefan/Documents/projects/cerebro/app/main.js:1814:24)
    at App._electron.app.on (/home/stefan/Documents/projects/cerebro/app/main.js:672:10)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```
My node version is 8.9.4.

**Comment by mxdlzg** [comment]
I got the same error
node v6.3.1
cerebro 3.2

**Comment by fuchsi3010** [comment]
Same issue for me - Ubuntu Budgie 17.10 with nodejs v6.11.4
When i install the .deb of 3.2.0 i get the Error discussed in #434 
When i use the fix described in #434 or i install the .deb of 3.1.0 i get a cerebro search window that - after i entered a search string - doesn't do anything. When I press the Enter key, the search box clears.

I tried to compile from source (I'm a very inexperienced user, have nerver installed from source) with the following steps: 1) git clone https://github.com/KELiON/cerebro.git cerebro 2) cd cerebro && yarn && cd ./app && yarn && cd ../ (runs nicely) 3) yarn run start 
the last command fail with this (last couple of lines i get from the terminal):
```
$ node ./node_modules/uglify-es/bin/uglifyjs ./app/dist/main.bundle.js -o ./app/dist/main.bundle.js --mangle && node ./node_modules/uglify-es/bin/uglifyjs ./app/dist/background.bundle.js -o ./app/dist/background.bundle.js --mangle
Rebuilding native production dependencies for linux:x64
Rebuilding native dependency ref
Rebuilding native dependency ffi
Packaging for linux x64 using electron 1.6.11 to release/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/fuchsi3010/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/fuchsi3010/Downloads/cerebro/release/cerebro-0.3.2-x86_64.AppImage -padding 0 -map /home/fuchsi3010/Downloads/cerebro/release/linux-unpacked /usr/bin -map /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-78e4oM/0-1-Cerebro.desktop /cerebro.desktop -map /home/fuchsi3010/Downloads/cerebro/build/icons/1024x1024.png /usr/share/icons/default/1024x1024/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/128x128.png /usr/share/icons/default/128x128/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/16x16.png /usr/share/icons/default/16x16/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/256x256.png /usr/share/icons/default/256x256/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/32x32.png /usr/share/icons/default/32x32/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/48x48.png /usr/share/icons/default/48x48/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/512x512.png /usr/share/icons/default/512x512/apps/cerebro.png -map /home/fuchsi3010/Downloads/cerebro/build/icons/1024x1024.png /.DirIcon -map /home/fuchsi3010/.cache/electron-builder/AppImage-packages/10.03.17 /usr/lib -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/fuchsi3010/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

/home/fuchsi3010/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:205:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
From previous event:
    at exec (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/targets/appImage.ts:79:5
    at next (native)
From previous event:
    at AppImageTarget.build (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/targets/appImage.js:144:11)
    at postAsyncTasks.push.default.map.it (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/platformPackager.ts:106:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/platformPackager.ts:106:41)
    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/platformPackager.ts:102:10
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.pack (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/platformPackager.js:169:11)
    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/packager.ts:257:24
    at next (native)
    at xfs.mkdir.er (/home/fuchsi3010/Downloads/cerebro/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager.doBuild (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/packager.js:379:11)
    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/packager.ts:170:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/packager.js:274:11)
    at /home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/src/builder.ts:198:33
    at next (native)
From previous event:
    at build (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/fuchsi3010/Downloads/cerebro/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
error An unexpected error occurred: "Command failed.
Exit code: 255
Command: sh
Arguments: -c yarn run build && build --publish never
Directory: /home/fuchsi3010/Downloads/cerebro
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/fuchsi3010/Downloads/cerebro/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
```

Help would be greatly appreciated - although I think it may just not (yet) work on 17.10?
Thanks for reading =)

**Comment by lovesora** [comment]
I also have this issue(ubuntu 18.04).
But when I quit the running cerebro. It works.

```bash
ps -ef | grep cerebro
# kill pid
```

```bash
# start dev
yarn run dev
```

**Comment by dubisdev** [comment]
I'm closing this as outdated. The development settings have been updated. Try with the new verison in `master` and if the problem persists, we can open a new issue.
