### ISSUE TITLE
Error when start app

### ISSUE THREAD

**Issue by pedroresende** [cerebroapp/cerebro#470]
I am on the latest Cerebro.app version
  I have searched the issues of this repo and believe that this is not a duplicate
Debian 9:
0.3.2:
Can't change settings

I still can get access to Cerebro by a shortkey but there are no icon in tray menu so i cant open devtool
If i try enable Developer mode by typing cerebro Settings i receive another error
http://ipic.su/img/img7/fs/kiss_29kb.1520249230.png

If i can somehow help then let me know

**Comment by paulomanrique** [comment]
Same error for me, on Fedora 28.

**Comment by nonbeing** [comment]
I'm getting two different startup exceptions. I installed `cerebro_0.3.2_amd64.deb` on Ubuntu 18.04.

Cerebro fails to launch on my system.

**Exception 1**
```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at EventEmitter.module.exports._electron.ipcMain.on (/opt/Cerebro/resources/app.asar/main.js:687:47)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/api/web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Exception 2**
```
Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/opt/Cerebro/resources/app.asar/main.js:251:15)
    at module.exports.exports.default (/opt/Cerebro/resources/app.asar/main.js:915:30)
    at App.module.exports._electron.app.on (/opt/Cerebro/resources/app.asar/main.js:653:43)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```
Don't know if this helps, but other Electron apps such as Slack and Tusk are working fine for me.

**Comment by neederhow** [comment]
I start `cerebro-0.3.2-x86_64.AppImage` **only one time** success in `Ubuntu 18.04 LTS`, when I reboot the system I can't start it anymore.
*System: Ubuntu 18.04 LTS*
*Cerebro version: cerebro-0.3.2-x86_64.AppImage*
**Exception message :**
```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/tmp/.mount_SFD6Xr/usr/bin/resources/app.asar/main.js:251:15)
    at module.exports.exports.default (/tmp/.mount_SFD6Xr/usr/bin/resources/app.asar/main.js:915:30)
    at App.module.exports._electron.app.on (/tmp/.mount_SFD6Xr/usr/bin/resources/app.asar/main.js:653:43)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by artyshko** [comment]
0.2.8 ver works great on my Ubuntu 18.04 while 0.3.2  don't

**Comment by geraltofrivia** [comment]
I've had a similar error. I used 0.3.1 and recently deleted it (and stuff from `.config/Cerebro` before running the 0.3.2 Appimage. The trace goes like:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/priyansh/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:21:30)
    at /tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/tmp/.mount_XRVB5t/usr/bin/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)
```

I use Elementary OS 0.4 Loki.

**Comment by tioguda** [comment]
Hi, I can start the cerebro 0.3.2 after making the corrections below in my Manjaro Linux.

**~/.config/Cerebro/config.json**

Change the line
`“trackingEnabled”: true,`

for
`“trackingEnabled”: false,`



**~/.config/Cerebro/config.json**

Change the line

```
“positions”: {
      “1657191935228674”: [
          355,
          136
     ]
}
```

for

`“positions”: {}`

**Comment by geraltofrivia** [comment]
@tioguda thanks! This worked for me.

**Comment by WispZhan** [comment]
In my Linux Mint, I have a similar error. by deb package installed Cerebro.
I used the method provided by @tioguda, It's worked for me.

**Comment by Indyandie** [comment]
Not sure if related but getting this on cerebro startup (macOS Mojave)
```
Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/lib/trackEvent.js:31:15)
    at module.exports.exports.default (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow.js:166:3)
    at App.module.exports._electron.app.on (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main.development.js:38:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

```

**Comment by LeshaRB** [comment]
I have some error on mac 0.3.2

![image](https://user-images.githubusercontent.com/439337/46652818-e1541e80-cbac-11e8-894b-0560efb7833a.png)

**Comment by zxqfox** [comment]
Why you using 0.3.2 (dec 17) when there is already 0.3.3 (may 18)?

I've just installed Cerebro via `brew cask install cerebro` and there are no 0.3.3, btw

**Comment by LeshaRB** [comment]
@zxqfox 
Official size - https://cerebroapp.com/
Mac version - https://github.com/KELiON/cerebro/releases/download/v0.3.1/cerebro-0.3.1.dmg

GitHub release https://github.com/KELiON/cerebro/releases
Version 0.3.2 


Where I can download 0.3.3?

**Comment by LeshaRB** [comment]
Is the project alive or dead?

**Comment by Conquistador** [comment]
Same errors... 
**Cerebro Version**: 3.2
**System**: Win10

**Comment by sajaddp** [comment]
Cerebro Version: 3.2
System: Win10

**Comment by alabotski** [comment]
I think Cerebro is no longer developing.

Found for myself a new program on Mint
https://albertlauncher.github.io/docs/installing/

**Comment by hitallow** [comment]
> Hi, I can start the cerebro 0.3.2 after making the corrections below in my Manjaro Linux.
> 
> **~/.config/Cerebro/config.json**
> 
> Change the line
> `“trackingEnabled”: true,`
> 
> for
> `“trackingEnabled”: false,`
> 
> **~/.config/Cerebro/config.json**
> 
> Change the line
> 
> ```
> “positions”: {
>       “1657191935228674”: [
>           355,
>           136
>      ]
> }
> ```
> 
> for
> 
> `“positions”: {}`

thanks, this worked for me.

**Comment by oguhpereira** [comment]
Hi @all 

I will try to help you with that


> Is the project alive or dead?

@alabotski is alive 😄 

another issue was created with some solutions, you already tried to do that:

https://github.com/cerebroapp/cerebro/issues/486#issuecomment-542516312

https://github.com/cerebroapp/cerebro/issues/486#issuecomment-492564242

**Comment by dubisdev** [comment]
This is an error related to tracking functionality. It was removed in [`v0.7.0`](https://github.com/cerebroapp/cerebro/releases/tag/v0.7.0) so we are closing this.
