### ISSUE TITLE
Error installing cerebro ubuntu 16.04

### ISSUE THREAD

**Issue by fduartej** [cerebroapp/cerebro#481]
After download the latest version and modify the chmod properties I am getting this error using ./app command as you can see below.......please can you helpme

 ./cerebro-0.3.2-x86_64.AppImage
/tmp/.mount_XhHawi/usr/bin/resources/electron.asar/common/reset-search-paths.js:0

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_XhHawi/usr/bin/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/tmp/.mount_XhHawi/usr/bin/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/tmp/.mount_XhHawi/usr/bin/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)

**Comment by yash1337** [comment]
Installing the .deb file from the releases worked for me. 
The 0.3.2 version seems to be broken on 17.10 and above. Try installing 0.3.1 and see if it gives you the same error.

**Comment by sudheerExperiments** [comment]
For some reason, the v0.3.2 didn't work for me on Ubuntu 19.04. The build seems broken. The v0.3.1, worked for me.

**Comment by crypdick** [comment]
@yash1337 I am still experiencing this problem after I downgraded to 0.3.1

 ```
~ cerebro    
/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:0



Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/opt/Cerebro/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)

```

**Comment by sudheerExperiments** [comment]
@crypdick, did you install Cerebro from source or did you install from deb file? Did you uninstall 0.3.2 version before installing 0.3.1?

**Comment by crypdick** [comment]
@sudheerExperiments I installed from .deb, and yes I uninstalled 0.3.2.

**Comment by sudheerExperiments** [comment]
Hello @crypdick,

I am not able to replicate your issue on my computer for some reason. I am also running Ubuntu 16.04 LTS. Let me know if you followed the same procedure as I did.

1. I downloaded *'cerebro_0.3.1_amd64.deb'* file from the build and installed the dependencies *'libappindicator1'* and *'libindicator7'* using the below command first.

```
sudo apt-get install libindicator7 libappindicator1
```
2. Then I installed *'cerebro_0.3.1_amd64'* using the below command.

```
sudo dpkg -i cerebro_0.3.1_amd64.deb
```

After installing Cerebro I literally had no issues with it on my computer. It's running perfectly. :+1:

**Comment by sudheerExperiments** [comment]
@crypdick,

I see your problem now. I finally replicate your issue. So here's what I think wrong with Cerebro.

The reason that Cerebro is throwing this error is, Cerebro is already launched and is running.. When I tried to launch another instance of Cerebro when is running, I got the same error. Check if Cerebro icon is already present in your Taskbar. If so, pressing 'Ctrl + space', it should launch Cerebro without any issues.

If you launch another instance by the terminal or from the launcher, then Cerebro throws the error you mentioned. Otherwise its working fine for me.

I hope this helps.

With Regards,
Sudheer.

**Comment by crypdick** [comment]
@sudheerExperiments D'oh! My previous launcher was bound to Super+space. Problem solved :)

**Comment by sudheerExperiments** [comment]
@crypdick, glad that my solution worked. 

I have a question, are you running Ubuntu on Mac?

**Comment by crypdick** [comment]
nope, I got a variety on Linux flavors on my machines (currently Ubuntu on a Dell XPS 13) but no Macs

**Comment by sudheerExperiments** [comment]
@crypdick Ohh cool. Thanks.

**Comment by rajeshisnepali** [comment]
> Installing the .deb file from the releases worked for me.
> The 0.3.2 version seems to be broken on 17.10 and above. Try installing 0.3.1 and see if it gives you the same error.

Thanks. .deb also worked for me. I had no installation issue with an AppImage. But it couldn't run.

**Comment by dubisdev** [comment]
I'm closing this as an outdate issue. Please try with `v0.7.1` and if the problem persists we can open another updated issue.
