### ISSUE TITLE
Cerebro doesn't start on Mint 21

### ISSUE THREAD

**Issue by ValTM** [cerebroapp/cerebro#572]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 21
- **Cerebro.app version**: cerebro-0.3.1-x86_64.AppImage
- **Relevant information from devtools**: N/A

## Issue
Hey,
I am trying to start the Cerebro 0.3.1 AppImage, but I am getting the following errors in terminal:
```
** (AppImageLauncher:100556): WARNING **: 03:33:34.593: Pixbuf theme: Cannot load pixmap file /home/valtm/.themes/Adapta-Nokto/gtk-2.0/ProgressBar/trough-dark.png: Failed to load image “/home/valtm/.themes/Adapta-Nokto/gtk-2.0/ProgressBar/trough-dark.png”: Fatal error in PNG image file: bad parameters to zlib

(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

** (AppImageLauncher:100556): WARNING **: 03:33:34.593: Invalid borders specified for theme pixmap:
        /home/valtm/.themes/Adapta-Nokto/gtk-2.0/ProgressBar/trough-dark.png,
borders don't fit within the image

(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
(AppImageLauncher:100556): GdkPixbuf-CRITICAL **: 03:33:34.593: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```

I tried with different themes, but to no avail.

**Comment by dubisdev** [comment]
Hi @ValTM 

Version 0.3.1 is outdated, please try the last version of the app so we can check if this error persists.

Try with
https://github.com/cerebroapp/cerebro/releases/download/v0.5.0/Cerebro-0.5.0.AppImage

The main branch is now in v0.6.0 but no executables were published. If you want you can try to build it from source following the instructions in the readme file.

Thanks 🙌
David

**Comment by ValTM** [comment]
Hey @dubisdev,

I downloaded 0.3.1, because that was what I found on the website. I thought it is the latest version. Sorry about that.
Anyways, with 0.5.0 AppImage I get a different error:
```
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[18073:0810/020807.531162:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

Failed to get crash dump id.
Report Id: --2022-08-10 02:

Failed to get crash dump id.
Report Id: --2022-08-10 02:
Illegal instruction (core dumped)
```
Specs are: 5900X, 64GB Ram, GTX1060 6GB, Linux Mint 21, Kernel 5.15.0-43-generic

**Comment by dubisdev** [comment]
I add it to the backlog. I'll try to reproduce it myself.

Thanks!

**Comment by ValTM** [comment]
Sure, let me know if I can help in any way.

**Comment by oguhpereira** [comment]
@ValTM could you validate in our latest version?

**Comment by ValTM** [comment]
@oguhpereira 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `lastShownDonateDialog` must be number
    at e.exports._validate (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:2:45448)
    at get store [as store] (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:2:44169)
    at new T (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:2:41902)
    at new e.exports (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:8:31842)
    at 9641 (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:2:30510)
    at r (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:8:68066)
    at /tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:8:68576
    at Object.<anonymous> (/tmp/.mount_CerebrLzuBPF/resources/app.asar/main.js:8:68602)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
```

Cerebro-0.10.0.AppImage

**Comment by oguhpereira** [comment]
We just uploaded a new version removing this view, can you check again @ValTM ?

**Comment by ValTM** [comment]
Can you provide a compiled verison @oguhpereira ?

**Comment by oguhpereira** [comment]
Check our last tag
https://github.com/cerebroapp/cerebro/releases/tag/v0.11.0

**Comment by ValTM** [comment]
Ah, I was looking for the artifacts in the Releases.

Anyways, it appears to be working all right, no issues!
I'll close this ticket as it seems resolved.
