### ISSUE TITLE
React.createContext is not a function

### ISSUE THREAD

**Issue by linonetwo** [cerebroapp/cerebro#656]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 13.2.1 Mac
- **Cerebro.app version**: 0.11.0
- **Relevant information from devtools** _(See above how to open it)_: 

```
Load plugin: @cerebroapp/cerebro-ui
externalPlugins.js:80 Path: /Users/linonetwo/Library/Application Support/Cerebro/plugins/node_modules/@cerebroapp/cerebro-ui...
externalPlugins.js:20 Error requiring /Users/linonetwo/Library/Application Support/Cerebro/plugins/node_modules/@cerebroapp/cerebro-ui
externalPlugins.js:21 TypeError: React.createContext is not a function
    at Object.<anonymous> (/Users/linonetwo/Lib…js/index.js:2726:48)
    at Object.<anonymous> (/Users/linonetwo/Lib…cjs/index.js:7745:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
externalPlugins.js:83 Plugin is not valid, skipped
```

**Comment by linonetwo** [comment]
Completely delete `/Users/linonetwo/Library/Application Support/Cerebro` fixes this.

**Comment by oguhpereira** [comment]
Are you having any problems right now? I don't understand if it was resolved.

**Comment by linonetwo** [comment]
Solved.
